version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # generator:
  #   build: ./generator
  #   depends_on:
  #     - redis
  #   command: ["python", "main.py"]

  # consumer:
  #   build: ./consumer
  #   depends_on:
  #     - redis
  #     - mongo
  #   command: ["python", "main.py"]

  # bulk_worker:
  #   build: ./bulk_worker
  #   container_name: bulk_worker
  #   depends_on:
  #     - mongo
  #   command: ["python", "main.py"]

volumes:
  mongo_data:
